### ISSUE TITLE
Add licensing footer to every DoCM page 

### ISSUE THREAD

**Issue by bainscou** [genome/docm#13]
We should license DoCM the same way that we license CIViC. Creative Commons Attribution 4.0 International License.

**Comment by bainscou** [comment]
Should we add a copyright too?

**Comment by malachig** [comment]
Yes, follow the style of CIViC

**Comment by malachig** [comment]
DoCM by The <a href="">McDonnell Genome Institute at Washington University School of Medicine</a> is licensed under a <a href="">Creative Commons Attribution 4.0 International License</a>.
Questions? Comments? Concerns? You can contact us <a href="">here</a>.

**Comment by acoffman** [comment]
Talked with @bainscou about this. For now I've added it to the 'About' page. When Josh gets back, we'll have him put it in the footer. Additionally we should probably clarify that the data is licensed under Creative Commons, but the code itself is MIT.
