### ISSUE TITLE
Tests are failing on build step

### ISSUE THREAD

**Issue by bainscou** [genome/docm#19]
TravisCI fails when trying to install better_errors referencing a requirement of Ruby version >= 2.0.0. @acoffman could that be fixed by changing the [following line](https://github.com/genome/docm/blob/master/.travis.yml#L7) to 2.0.0?

**Comment by acoffman** [comment]
You can just delete that line if you'd like! We were running the tests on both versions of ruby (1.9.x and 2.1.x) but I'm fine dropping compatibility for 1.9.x as I don't think anyone is using that version here at MGI.
