### ISSUE TITLE
Add google analytics to DoCM

### ISSUE THREAD

**Issue by bainscou** [genome/docm#2]
Please and thank you!

**Comment by acoffman** [comment]
Set up in the TGI account and added to docm in ea9ec596bbb4a230d5c14c1e8cfcec053014f94a. Added yourself, Obi and Malachi to the account as admins.

We'll schedule a deploy early next week to get this out to production!

**Comment by malachig** [comment]
Awesome.  Thanks @acoffman.  As we continue to develop DOCM, DGIdb, CIViC we will be thinking about how to integrate them with each other in a way that is most useful.  This will help us get a sense of how each is being used by whom...
