### ISSUE TITLE
Add new data sources to DoCM

### ISSUE THREAD

**Issue by malachig** [genome/docm#22]
Some additional variant lists have been curated but have not yet been imported into the liver version of DoCM.  Prior to publication we should do these imports and update the News feed as we add them.

**Comment by malachig** [comment]
Data sources to be added:
- OncoMap variants (LE MacConail et al. 2014)
- CIViC variants
- Others?

**Comment by acoffman** [comment]
All of the listed sources (and additional ones) are now incorporated!
