### ISSUE TITLE
TSV exports contain html-sanitized characters

### ISSUE THREAD

**Issue by chrisamiller** [genome/docm#3]
Do any search (I pulled down 'acute myeloid leukemia'), then export at TSV of the list.  The first line of the text file contains the following: 
ENST00000373103:c.1853G\&gt;A 

Instead of the expected
ENST00000373103:c.1853G>A

**Comment by acoffman** [comment]
Good catch! Fixed in 5b209ae1c7b0f55c3522b9b1d0517fb61971b17e. Will deploy the fix to to production box today.

Thanks!

**Comment by acoffman** [comment]
Deployed!
