### ISSUE TITLE
API Doesn't Return drug_interactions field

### ISSUE THREAD

**Issue by mattdmem** [genome/docm#32]
You example includes a drug_interactions field in the response, but if you try this example no drug interaction data is returned.

/api/v1/variants/ENST00000263967:c.1633G>C.json

**Comment by acoffman** [comment]
Thanks for the report! I'll be taking a look at this today and let you know what I find.

**Comment by mattdmem** [comment]
great thanks for your help.

**Comment by ahwagner** [comment]
Same issue. Using prior versions also does not address problem.

**Comment by acoffman** [comment]
@ahwagner @mattdmem I've identified the issue here and its related to a change in the import format. I'm working on a fix and I'll have it out today!

**Comment by acoffman** [comment]
@ahwagner @mattdmem I've just released a fix for this issue and its now out on the live site.

API responses now include drug interactions as they did before. Oddly enough, the particular example documented in the API docs does not have any interactions in the dataset (though it clearly did at one point based on the sample response). I have double checked that this isn't a bug with the importer - there really is no drug interaction information for those rows in the spreadsheet. Maybe @bainscou wants to weigh in on that?

In the meantime, I've also updated the API documentation with a new example that does have drug interactions.

**Comment by bainscou** [comment]
@acoffman it looks to me like that metadata is in the TSV file, line 3214 of docm_v3.tsv. Am I looking at the wrong thing?

**Comment by acoffman** [comment]
@bainscou Ah-ha! I missed it on my first go around.

That particular metadata section is getting filtered out because it doesn't have a valid pubmed id - there's a text citation for an abstract rather than an id. Is there a pubmed id we could use? Or do we need to come up with a way support sources/citations that aren't strictly from pubmed?

**Comment by bainscou** [comment]
It looks like that is an abstract from a conference. I suggest we don't import that particular metadata since it doesn't yet have a publication. The other metadata for that variant should still be included.

**Comment by acoffman** [comment]
@bainscou, sounds good! I'll make the change and get another release out today.
