### ISSUE TITLE
WS Returns 404 - Better option for variants not in db?

### ISSUE THREAD

**Issue by mattdmem** [genome/docm#33]
If a variant isn't found the API returns 404, it would be useful to return something that indicates your request was good but the variant wasn't found.

**Comment by acoffman** [comment]
I believe that a `404 Not Found` HTTP status code is correct in the case of a well formed request that doesn't find any results (as opposed to a malformed request which should yield a `400 Bad Request` status code).

However, there's nothing inherent to a 404 status that requires an empty response body. Would a message of some sort in the body of the response be useful for what you're doing?

**Comment by mattdmem** [comment]
I wasn't aware of that, I'll check for 404 vs 400.  I've written a little python wrapper around the API so I can use it in a variant annotation project I'm working on.

**Comment by acoffman** [comment]
We'll still return a `404` when a variant is not found, but the response body will now include some feedback indicating that, while it was a well formed request, the HGVS in question was not found in DoCM.

This will go out in the next deploy!
