### ISSUE TITLE
Truncate amino acid column for main grid

### ISSUE THREAD

**Issue by bainscou** [genome/docm#34]
variants like http://docm.genome.wustl.edu/variants/ENST00000261609:c.2277delAACGGTCCTGACCTG?version=2

screw up the formatting.

@acoffman could this be incorporated in the next release?

**Comment by acoffman** [comment]
@bainscou No problem! Do you have a desired width to truncate to, or shall I just pick one that looks good?

**Comment by acoffman** [comment]
Fixed. Currently truncating to a maximum of 9 characters as that's what seems to work best in the grid. Let me know if you prefer a different length!
