### ISSUE TITLE
Reverse the Sort Order on the Version Select Dropdown

### ISSUE THREAD

**Issue by ahwagner** [genome/docm#50]
The current (most recent) version is at the top, and then the versions are listed in ascending order. It seems more intuitive to me that the versions would be listed in descending order, with the second entry starting at the penultimate version.

<img width="1349" alt="screen shot 2016-03-29 at 3 52 27 pm" src="https://cloud.githubusercontent.com/assets/811065/14123477/537cfe24-f5c6-11e5-9909-d98348ab2a09.png">

**Comment by acoffman** [comment]
No problem, that's a super easy fix!
