### ISSUE TITLE
Truncate HGVS view to 30 chars to improve view and layout 

### ISSUE THREAD

**Issue by bainscou** [genome/docm#9]

**Comment by bainscou** [comment]
@acoffman Could you include this on the next update too? There is an index in CTNNB1 that really screws up the layout.

**Comment by acoffman** [comment]
@bainscou Sure thing - I assume you just want this in the main data table on the frontpage, not the single variant pages, correct?

**Comment by bainscou** [comment]
@acoffman Yes, exactly.
